parameters:
    amp_pdf_crowd.api.class: Hiren\PDFCrowdBundle\Lib\PDFCrowd

services:
    hiren_pdf_crowd.api:
        class: %hiren_pdf_crowd.api.class%
        arguments: [ %hiren_pdf_crowd.username%, %hiren_pdf_crowd.apikey% ]
